// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react"
import * as Client from "react-dom/client"

function ReactApp$App(props) {
  return React.createElement("div", undefined, "Hello World!")
}

var App = {
  make: ReactApp$App,
}

var root = document.querySelector("#root")

if (root == null) {
  console.error("Failed to start React: couldn't find the #root element")
} else {
  var root$1 = Client.createRoot(root)
  root$1.render(React.createElement(ReactApp$App, {}))
}

export { App }
/* root Not a pure module */
